---- Helpdesk Hard Questions 
---- Schema & Tasks Link: https://sqlzoo.net/wiki/Help_Desk

--- 11. Show the manager and number of calls received for each hour of the day on 2017-08-12


-- Step 1: Get shift details for the target date
with shift_details as (
	select 
		s.Shift_date, 
		s.Shift_type, 
		s.Manager, 
		t.Start_time, 
		t.End_time
	from Shift as s 
	inner join Shift_type as t 
		on s.Shift_type = t.Shift_type
	where date(Shift_date) = '2017-08-12'
)

-- Step 2: Count calls per manager by hour
select 
	sd.Manager, 
	DATE_FORMAT(i.call_date, '%Y-%m-%d %H') as Hr, 
	count(*) as cc
from Issue as i 
inner join shift_details as sd
	on time(i.call_date) >= sd.Start_time 
	and time(i.call_date) < sd.End_time
where date(Call_date) = '2017-08-12'
group by 1, 2
order by Hr

--- 12. 80/20 rule. It is said that 80% of the calls are generated by 20% of the callers. Is this true? What percentage of calls are generated by the most active 20% of callers.

-- Step 1: Count issues per caller and assign a rank by volume
with call_counts as (
	select 
		Caller_id, 
		count(*) as cc, 
		row_number() over(order by cc desc) as rn
	from Issue
	group by Caller_id
),

-- Step 2: Get total number of issues
total_issues as (
	select count(*) as total_issues
	from Issue
),

-- Step 3: Get total number of callers
total_callers as (
	select count(*) as total_callers 
	from Caller
)

-- Step 4: Calculate the percentage of issues from the top 20% callers
select 
	(sum(cc) * 100.0 / (select total_issues from total_issues)) as t20pc
from call_counts 
where rn <= (
	select floor(total_callers * 0.20)
	from total_callers
)
